version: '3.4'
# Define common behavior with https://docs.docker.com/compose/compose-file/compose-file-v3/#extension-fields
x-rehost-web-service: &latest-rehost-service
  env_file: .env
  build:
    target: base
    context: .
  # Other settings can also be shared
  image: woss/rehost-service:latest

services:
  rehost_latest: *latest-rehost-service
  rehost:
    <<: *latest-rehost-service
    image: woss/rehost-service:${REHOST_IMAGE_VERSION}
    build:
      context: .
    env_file: ./.env
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - 3000:3000
  mongodb:
    image: mongo
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb/
volumes:
  mongodb_data:
